model_config:
  target: InstantMesh.src.models.lrm_mesh.InstantMesh
  params:
    encoder_feat_dim: 768
    encoder_freeze: false
    encoder_model_name: facebook/dino-vitb16
    transformer_dim: 1024
    transformer_layers: 12
    transformer_heads: 16
    triplane_low_res: 32
    triplane_high_res: 64
    triplane_dim: 40
    # Reduced ray samples to save VRAM
    rendering_samples_per_ray: 32
    # 96 is the "Sweet Spot" for 6GB GPUs (Stable and Detailed)
    grid_res: 112
    # 1.2 Tightens the box around the jewelry, cutting off background spikes
    grid_scale: 1.2

infer_config:
  unet_path: ckpts/diffusion_pytorch_model.bin
  model_path: ckpts/instant_mesh_base.ckpt
  texture_resolution: 1024
  render_resolution: 512